site:
  title: Antora Markdown Exporter
  url: https://wstein.github.io/antora-markdown-exporter
  start_page: antora-markdown-exporter::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: build/site
